[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # Custom (example):
  #| tests\/data\/test_data_preprocess\.py
)
'''